---
- import_tasks: installation.yml
  tags: [firewalld, firewalld-install, install]

- import_tasks: configuration.yml
  tags: [firewalld, firewalld-config, config]

- import_tasks: service.yml
  tags: [firewalld, firewalld-service, service]

- import_tasks: rules.yml
  tags: [firewalld, firewalld-rules, firewalld-config, config]
