---
- import_tasks: install.yml
  tags: [firewalld, firewalld-install, install]

- import_tasks: configure.yml
  tags: [firewalld, firewalld-config, config]

- import_tasks: service.yml
  tags: [firewalld, firewalld-service, service]

- import_tasks: manage_rules.yml
  tags: [firewalld, firewalld-rules, firewalld-config, config]
